/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author augus
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    private double valorInicial;
    public double primeira;
    public double segunda;
    public double valor;
    public double atual;
    public int contador = 0;
    public double total = 0;
    public main() {
        setTitle("Bank Control");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Valor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        valorAtual = new javax.swing.JLabel();
        Win = new javax.swing.JButton();
        ReRoll = new javax.swing.JButton();
        valorRoll = new javax.swing.JLabel();
        rodada = new javax.swing.JLabel();
        totalGasto = new javax.swing.JLabel();
        stopLoss = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor");

        valorAtual.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        valorAtual.setText("Valor Atual:");

        Win.setBackground(new java.awt.Color(0, 204, 0));
        Win.setForeground(new java.awt.Color(0, 0, 0));
        Win.setText("Vitória");
        Win.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WinActionPerformed(evt);
            }
        });

        ReRoll.setText("Roll");
        ReRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReRollActionPerformed(evt);
            }
        });

        valorRoll.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        valorRoll.setText("Roll: ");

        rodada.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rodada.setText("Rodada: 0");

        totalGasto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalGasto.setText("Total Gasto:");

        stopLoss.setBackground(new java.awt.Color(153, 0, 0));
        stopLoss.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stopLoss.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valorAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rodada, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(ReRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Win, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stopLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(valorAtual)
                        .addGap(12, 12, 12)))
                .addComponent(totalGasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorRoll)
                .addGap(54, 54, 54)
                .addComponent(stopLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Win, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rodada)
                        .addGap(15, 15, 15))))
        );

        Valor.getAccessibleContext().setAccessibleName("");
        stopLoss.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void atualizarLabel() {
        valorAtual.setText(String.format("Valor Atual: R$ %.2f", valor));
          if (valor <= valorInicial * 0.75) {
        stopLoss.setText("⚠️ PARE IMEDIATAMENTE! 60% DA BANCA ALCANÇADO!");

    } else {
        stopLoss.setText("");  // Opcional, limpa o texto caso não atinja a condição
    }
    }
    public void atualizarRoll(){
        valorRoll.setText(String.format("Valor Roll: R$ %.2f", atual));
    }
    private void ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorActionPerformed
        valor = Double.parseDouble(Valor.getText());
        if (contador == 0) { // Define o valor inicial apenas uma vez
            valorInicial = valor;
            }
        atualizarLabel();
    }//GEN-LAST:event_ValorActionPerformed

    private void WinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WinActionPerformed
        // TODO add your handling code here:
        valor += (atual * 3);
        contador = 0;
        total = 0;
        atualizarLabel();
    }//GEN-LAST:event_WinActionPerformed

    private void ReRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReRollActionPerformed

        // Incrementa o contador
    contador += 1;

    // Atualiza o texto do botão ReRoll
    ReRoll.setText("ReRoll");

    // Caso seja a primeira rodada (contador == 1)

    if (contador == 1) {
        primeira = 1;
        segunda = 1;
        atual = 1;
    } 
    // Caso seja a segunda rodada (contador == 2)
    else if (contador == 2) {
        // Não altera os valores de primeira e segunda, apenas continua com o mesmo valor atual
        total += atual;
    } 
    // Caso seja a terceira rodada ou mais (contador > 2)
    else {
        // Calcula o próximo valor da sequência de Fibonacci
        atual = primeira + segunda;
        primeira = segunda;
        segunda = atual;
    }

    // Atualiza o valor e o total gasto
    valor -= atual;
    total += atual;

    // Atualiza os textos da interface gráfica
    rodada.setText(String.format("Rodada: %d", contador));
    if (contador == 1)
        totalGasto.setText("Total Gasto: R$ 1.00");
    else
    totalGasto.setText(String.format("Total Gasto: R$ %.2f", total - 1));
    atualizarLabel();
    atualizarRoll();                 
    }//GEN-LAST:event_ReRollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReRoll;
    public javax.swing.JTextField Valor;
    private javax.swing.JButton Win;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel rodada;
    private javax.swing.JLabel stopLoss;
    private javax.swing.JLabel totalGasto;
    private javax.swing.JLabel valorAtual;
    private javax.swing.JLabel valorRoll;
    // End of variables declaration//GEN-END:variables
}
